import React, { useState, useEffect, useMemo } from 'react';
import type { ChatMessage as Message } from '../types';
import { GenieLampIcon } from './icons/GenieLampIcon';
import { RefreshIcon } from './icons/RefreshIcon';
import { ChevronLeftIcon } from './icons/ChevronLeftIcon';
import { ChevronRightIcon } from './icons/ChevronRightIcon';
import { SparklesIcon } from './icons/SparklesIcon';
import { PinIcon } from './icons/PinIcon';
import { useSparkles } from '../contexts/SparkleContext';
import { PendingIcon } from './icons/PendingIcon';
import { EmojiAddIcon } from './icons/EmojiAddIcon';

interface TypingTextProps {
  fullText: string;
  onComplete: () => void;
}

const TypingText: React.FC<TypingTextProps> = ({ fullText, onComplete }) => {
  const [displayedText, setDisplayedText] = useState('');
  const [isCompleted, setIsCompleted] = useState(false);

  useEffect(() => {
    setDisplayedText('');
    setIsCompleted(false);
  }, [fullText]);
  
  useEffect(() => {
    if (isCompleted) return;

    if (displayedText.length < fullText.length) {
      const delay = Math.random() * 15 + 5; // Random delay between 5ms and 20ms
      const timeout = setTimeout(() => {
        setDisplayedText(fullText.slice(0, displayedText.length + 1));
      }, delay);
      return () => clearTimeout(timeout);
    } else {
      onComplete();
      setIsCompleted(true);
    }
  }, [displayedText, fullText, onComplete, isCompleted]);
  
  const paragraphs = useMemo(() => {
    const lines = displayedText.split('\n');
    const cursor = !isCompleted ? <span className="cursor-blink">▋</span> : null;
    
    return lines.map((paragraph, index) => (
      <p key={index} className="mb-2 last:mb-0 min-h-[1.2em]">
        {paragraph}{index === lines.length - 1 ? cursor : ''}
      </p>
    ));
  }, [displayedText, isCompleted]);

  return <>{paragraphs}</>;
};

interface ChatMessageProps {
  message: Message;
  isLastMessage: boolean;
  onRegenerate: () => void;
  onNavigateResponse: (messageId: string, direction: 'prev' | 'next') => void;
  onTypingComplete: () => void;
  onTogglePin: () => void;
  onToggleReaction: (emoji: string) => void;
  isBeingRegenerated?: boolean;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message, isLastMessage, onRegenerate, onNavigateResponse, onTypingComplete, onTogglePin, onToggleReaction, isBeingRegenerated = false }) => {
  const isModel = message.role === 'model';
  const isPending = message.isPending;
  const [showReactionPicker, setShowReactionPicker] = useState(false);
  const availableReactions = ['👍', '❤️', '😂', '✨', '🤔'];
  
  const currentIndex = message.activeResponseIndex ?? 0;
  const allResponses = useMemo(() => {
    if (isModel && message.responses && message.responses.length > 0) {
      return message.responses;
    }
    // For user messages or older model messages without the `responses` array
    return [{ text: message.text, imageUrl: message.imageUrl }];
  }, [message, isModel]);

  const activeResponse = allResponses[currentIndex];
  const canRegenerate = isModel && isLastMessage && !React.isValidElement(activeResponse?.text);

  const hasMultipleResponses = isModel && allResponses.length > 1;
  const totalResponses = allResponses.length;
  const canGoPrev = currentIndex > 0;
  const canGoNext = currentIndex < totalResponses - 1;

  const { showSparkles } = useSparkles();

  const handleIconClick = (e: React.MouseEvent) => {
      showSparkles({ x: e.clientX, y: e.clientY });
  };
  
  const renderResponseSlide = (response: (typeof allResponses)[0], isCurrentlyActive: boolean) => {
    const isTyping = response.isTyping && isCurrentlyActive;

    const renderTextContent = () => {
      if (isTyping && typeof response.text === 'string' && !response.imageUrl) {
        return <TypingText fullText={response.text} onComplete={onTypingComplete} />;
      }
      if (typeof response.text === 'string') {
        return response.text.split('\n').map((p, i) => <p key={i} className="mb-2 last:mb-0 min-h-[1.2em]">{p}</p>);
      }
      return response.text;
    };

    return (
        <div className="w-full flex-shrink-0">
            {response.imageUrl ? (
                <div className="p-1">
                    <img src={response.imageUrl} alt="Generated by Genie" className="rounded-lg max-w-full h-auto" />
                </div>
            ) : (
                <div className="px-4 py-3 text-sm leading-relaxed">
                    {renderTextContent()}
                </div>
            )}
        </div>
    );
  };


  return (
    <div id={`message-${message.id}`} className={`flex flex-col group ${isModel ? 'items-start' : 'items-end'} ${message.isInitial ? 'animate-fade-in-up' : ''}`}>
        <div className={`flex items-end gap-2 ${isModel ? '' : 'justify-end'}`}>
          {isModel && (
            <button
                onClick={handleIconClick}
                className="w-8 h-8 flex-shrink-0 bg-accent-primary/80 rounded-full flex items-center justify-center shadow-lg self-start sparkle-trigger focus:outline-none focus:ring-2 focus:ring-accent-secondary"
                aria-label="Sparkle effect"
            >
                <GenieLampIcon className="w-5 h-5 text-accent-text" />
            </button>
          )}
          <div
            className={`max-w-xs md:max-w-md rounded-xl shadow-md relative ${
              isModel
                ? 'bg-background-secondary text-text-primary rounded-bl-none'
                : `bg-accent-primary text-accent-text rounded-br-none ${isPending ? 'opacity-70' : ''}`
            }`}
          >
            {isBeingRegenerated && (
                <div className="absolute inset-0 bg-background-secondary/80 backdrop-blur-sm rounded-xl flex flex-col items-center justify-center z-10 text-text-primary">
                    <SparklesIcon className="w-5 h-5 text-accent-primary animate-pulse" />
                    <span className="text-xs font-semibold mt-1">Regenerating...</span>
                </div>
            )}
            <div className="overflow-hidden rounded-xl">
              <div
                className="flex transition-transform duration-500 ease-in-out"
                style={{ transform: `translateX(-${currentIndex * 100}%)` }}
                role="region"
                aria-live="polite"
                aria-atomic="true"
              >
                {allResponses.map((response, index) => (
                  <div key={index} aria-hidden={index !== currentIndex}>
                    {renderResponseSlide(response, index === currentIndex)}
                  </div>
                ))}
              </div>
            </div>
          </div>
          {isPending ? (
              <div className="flex items-center gap-1 self-center mb-1" aria-label="Sending message...">
                  <PendingIcon className="w-4 h-4 text-text-secondary animate-spin" style={{ animationDuration: '2s' }} />
              </div>
          ) : (
            <div className="flex items-center gap-1 self-center mb-1 opacity-0 group-hover:opacity-100 focus-within:opacity-100 transition-opacity relative">
                <button
                    onClick={() => setShowReactionPicker(prev => !prev)}
                    className="p-1.5 rounded-full bg-background-secondary border border-border-primary hover:bg-background-hover text-text-secondary"
                    aria-label="Add reaction"
                >
                    <EmojiAddIcon className="w-4 h-4" />
                </button>
                {showReactionPicker && (
                    <div className="absolute bottom-full mb-2 flex gap-1 bg-background-tertiary p-1.5 rounded-full shadow-lg border border-border-primary z-20">
                        {availableReactions.map(emoji => (
                            <button
                                key={emoji}
                                onClick={() => {
                                    onToggleReaction(emoji);
                                    setShowReactionPicker(false);
                                }}
                                className={`p-1 text-lg rounded-full transition-transform transform hover:scale-125 ${message.reactions?.includes(emoji) ? 'bg-accent-primary/20' : ''}`}
                            >
                                {emoji}
                            </button>
                        ))}
                    </div>
                )}
                <button
                    onClick={onTogglePin}
                    className={`p-1.5 rounded-full bg-background-secondary border border-border-primary hover:bg-background-hover ${message.isPinned ? 'text-accent-primary' : 'text-text-secondary'}`}
                    aria-label={message.isPinned ? "Unpin message" : "Pin message"}
                >
                    <PinIcon isPinned={!!message.isPinned} className="w-4 h-4" />
                </button>
                {hasMultipleResponses && (
                    <div className="flex items-center gap-1 text-text-secondary bg-background-secondary p-1 rounded-full border border-border-primary">
                        <button onClick={() => onNavigateResponse(message.id, 'prev')} disabled={!canGoPrev} className="p-0.5 rounded-full hover:bg-background-hover disabled:opacity-30 disabled:cursor-not-allowed" aria-label="Previous response">
                            <ChevronLeftIcon className="w-4 h-4" />
                        </button>
                        <span className="text-xs font-mono select-none" aria-label={`Response ${currentIndex + 1} of ${totalResponses}`}>{currentIndex + 1}/{totalResponses}</span>
                        <button onClick={() => onNavigateResponse(message.id, 'next')} disabled={!canGoNext} className="p-0.5 rounded-full hover:bg-background-hover disabled:opacity-30 disabled:cursor-not-allowed" aria-label="Next response">
                            <ChevronRightIcon className="w-4 h-4" />
                        </button>
                    </div>
                )}
                {canRegenerate && (
                    <button
                        onClick={onRegenerate}
                        className="p-1.5 rounded-full text-text-secondary bg-background-secondary border border-border-primary hover:bg-background-hover hover:text-text-primary"
                        aria-label="Regenerate response"
                    >
                        <RefreshIcon className="w-4 h-4" />
                    </button>
                )}
            </div>
          )}
        </div>
        {message.reactions && message.reactions.length > 0 && (
            <div className={`flex gap-1.5 mt-1 ${isModel ? 'ml-10' : ''}`}>
                {message.reactions.map(emoji => (
                    <button
                        key={emoji}
                        onClick={() => onToggleReaction(emoji)}
                        className="bg-background-secondary px-2 py-0.5 rounded-full text-xs border border-accent-primary/50 hover:border-accent-primary transition-colors"
                        aria-label={`Remove ${emoji} reaction`}
                    >
                        {emoji}
                    </button>
                ))}
            </div>
        )}
    </div>
  );
};

export default ChatMessage;
